### ISSUE TITLE
No waterCurrentDiluvio scripts in the file

### ISSUE THREAD

**Issue by xkevincode** [disaster-robotics-proalertas/usv_sim_lsa#25]
Hi, I could not find waterCurrentDiluvio in all the folders, did you change the name to water_HECRAS.py ? 
If so, is this the same way I can generate different scenarios just like in #11 ?
many thanks

**Comment by marceloparavisi** [comment]
Hello xkevincode

That script has been removed, since the project has been modified. Download the HECRAS files from (https://drive.google.com/drive/folders/1CjJbe2wZsUF7bmqYOP_vRPixGPzGU8Gt?usp=sharing)

Edit yaml files inside the folder "src/usv_sim_lsa/usv_env_disturb/water_current/maps/HECRAS/". 

After that, you may run something like: 
`rosrun water_current water_HECRAS.py src/usv_sim_lsa/usv_env_disturb/water_current/maps/HECRAS/diluvio1.yaml`

Regards,
Marcelo
